baseURL = "https://www.pusnow.com/"
languageCode = "en-us"
title = "Pusnow"
theme = "xmin-pusnow"
enableGitInfo = true

[permalinks]
note = "/note/:filename/"
publication = "/publication/:filename/"

[[menu.main]]
name = "Home"
url = ""
weight = 1

[[menu.main]]
name = "Tags"
url = "tags/"
weight = 2

[[menu.main]]
name = "About"
url = "about/"
weight = 3

[params]
footer = "&copy; [Wonsup Yoon](https://www.pusnow.com) | [GitHub](https://github.com/pusnow) | Original theme: [Hugo xmin](https://github.com/yihui/hugo-xmin)"

[markup]
defaultMarkdownHandler = "goldmark"

[markup.goldmark.extensions]
definitionList = true
footnote = true
linkify = true
strikethrough = true
table = true
taskList = true
typographer = true